version: '3'
services:
  limesurvey:
    image: docker.io/martialblog/limesurvey:latest
    restart: always
    environment:
      - DB_TYPE=pgsql
      - DB_PORT=5432
      - DB_HOST=db
      - DB_PASSWORD=Cie123
      - DB_NAME=limesurvey
      - DB_USERNAME=limesurvey
      - ADMIN_USER=admin
      - ADMIN_NAME=Admin
      - ADMIN_PASSWORD=Cie@12345
      - ADMIN_EMAIL=minhtoan.developer@gmail.com
      - PUBLIC_URL=limesurvey.dtqt.edu.vn
    volumes:
      - ./data/limesurvey:/var/www/html/upload/surveys
      - ./html:/var/www/html
    ports:
      - 7181:8080
    depends_on:
      - db
  db:
    image: docker.io/postgres:10-alpine
    restart: always
    volumes:
      - ./data/db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=limesurvey
      - POSTGRES_DB=limesurvey
      - POSTGRES_PASSWORD=Cie123
